--INSERT INTO users (id, name, email) VALUES (1, 'John', 'John@example.com');
--INSERT INTO users (id, name, email) VALUES (2, 'France', 'France@example.com');
--INSERT INTO users (id, name, email) VALUES (3, 'Brazil', 'Brazil@example.com');
--INSERT INTO users (id, name, email) VALUES (4, 'Italy', 'Italy@example.com');
--INSERT INTO users (id, name, email) VALUES (5, 'Canada', 'Canada@example.com');
--
--
